{
    "name": "EL Nasr Private School Management System",
    "version": "1.0",
    "category": "Education",
    "summary": "Manage school operations including students, teachers, and classes",
    "description": "",
    "depends": ["base", "mail", "web", "auth_signup"],
    "author": "EL Nasr",
    "license": "LGPL-3",
    "data": [
        "security/groups.xml",
        "security/Enrollment_Security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/base_view.xml",
        "views/dashboard_view.xml",
        "views/students_view.xml",
        "views/courses_view.xml",
        "views/instructor_view.xml",
        "views/enrollment_view.xml",
        "views/timetable_view.xml",
        'views/attendance_view.xml',
        'views/grade_view.xml',
        "views/auth_signup_inherit.xml",
        "views/login_inherit.xml",
        "weized/course_wizerd_view.xml",
        "views/res_users.xml",
        "reports/timetable.xml",
        "reports/student.xml",
        "reports/attendance.xml",
    ],
    "web_icon": "/school/static/description/icon.png",
    "application": True,
    "installable": True,
    "supports_translations": True,
}
